alias ls="exa --icons -lh"
alias lt="exa --icons -lh --tree --level=2"
alias ll="exa --icons -lha"
alias cat="batcat"
alias udp="sudo apt update && sudo apt upgrade && sudo apt autoremove -y"
alias grep="rg"
alias nano="micro"
alias code="flatpak run com.visualstudio.code"
